Repository webcompat/webcompat.com, pull requests merged in 2018-05, with the labels that each got.

#2438 Fixes #2421 - Consolidate usage of js-loader
  webcompat/static/js/lib/bugform.js
  webcompat/static/js/lib/issue-list.js
  webcompat/static/js/lib/issues.js
  webcompat/static/js/lib/user-activity.js
  webcompat/templates/home-page/form.html
  webcompat/templates/index.html
  webcompat/templates/issue/upload-image.jst
  webcompat/templates/list-issue.html
  webcompat/templates/new-issue.html
  webcompat/templates/user-activity.html
Labels: in progress

#2458 Fixes #2459 - Add .prettierrc
  .prettierrc
Labels: status: needs review, type: site-development

#2461 Fixes: #2460 – Add pull request template
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
Labels: in progress, status: needs decision, type: enhancement, type: site-development
