Repository webcompat/webcompat.com, pull requests merged in 2018-06, with the labels that each got.

#2439 Fixes #2409. Don't pre-fill forms for "self reports" (webcompat.com)
  webcompat/static/js/lib/bugform.js
Labels: in progress

#2489 webcompat site: tweak/remove aria-label in footer links, make search form in top nav only focusable when visible
  webcompat/static/css/src/nav.css
  webcompat/templates/shared/footer.html
Labels: status: add to changelog

#2491 Fixes #2490 - inversed name of buttons
  webcompat/templates/home-page/form.html
Labels: status: needs review

#2527 Fixes #2526 - fixed filteringSort function
  webcompat/static/js/lib/dashboard.js
  webcompat/templates/dashboard/triage/filters.html
Labels: lang: JS, scope: dashboard, status: needs review
